HitRave/Controllers/ClothingAndAccessoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HitRave.Controllers
{
    public class ClothingAndAccessoriesController : Controller
    {
        // GET: /ClothingAndAccessories/
        public ActionResult Index()
        {
            return View();
        }

        // GET: /ClothingAndAccessories/Shop/
        public ActionResult Shop()
        {
            return View();
        }
    }
}

HitRave/Controllers/ElectronicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HitRave.Controllers
{
    public class ElectronicsController : Controller
    {
        // GET: /Electronics/
        public ActionResult Index()
        {
            return View();
        }

        // GET: /Electronics/Shop/
        public ActionResult Shop()
        {
            return View();
        }
    }
}

HitRave/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HitRave.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HitRave/Controllers/MakeupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HitRave.Controllers
{
    public class MakeupController : Controller
    {
        // GET: /Makeup/
        public ActionResult Index()
        {
            return View();
        }

        // GET: /Makeup/Shop/
        public ActionResult Shop()
        {
            return View();
        }
    }
}

HitRave/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HitRave/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Some Pl.<br />
    Scappoose, OR 98104<br />
    <abbr title="Phone">P:</abbr>
    555.555.5555
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">rodgjame@isu.edu</a><br />
</address>

HitRave/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to HitRave.com</h1>
    <p class="lead">Here is where we can put some welcome text. Or we'll have a sales message</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Electronics</h2>
        <a href=@Url.Action("Shop", "Electronics")>
            <img alt="Electronics" class="img-index img-circle img-responsive" src="@Url.Content("~/Content/Images/glasses.jpg")" />
        </a>
        <p>Shop for electronic lights, toys, and everything in between</p>
        <p><a class="btn btn-default" href=@Url.Action("Shop", "Electronics")>Light Me Up! &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Paints and Colors</h2>
        <a href=@Url.Action("Shop", "Makeup")>
            <img alt="Paints and Colors" class="img-index img-circle img-responsive" src="@Url.Content("~/Content/Images/paint.jpg")" />
        </a>
        <p>Markers, makeup, etc.</p>
        <p><a class="btn btn-default" href=@Url.Action("Shop", "Makeup")>Color Me Up! &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Clothing and Accessories</h2>
        <a href=@Url.Action("Shop", "ClothingAndAccessories")>
            <img alt="Clothing and Accessories" class="img-index img-circle img-responsive" src="@Url.Content("~/Content/Images/girl.jpg")" />
        </a>
        <p>Need to decide on a third catagory</p>
        <p><a class="btn btn-default" href=@Url.Action("Shop", "ClothingAndAccessories")>Dress Me Up! &raquo;</a></p>
    </div>
</div>